Backend/CIPlatform/Controllers/MissionController.cs
using CIPlatform.DataModels;
using CIPlatform.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MailKit.Net.Smtp;
using MailKit.Security;
using MimeKit;
using MimeKit.Text;

namespace CIPlatform.Controllers
{
    public class MissionController : Controller
    {
        public CiPlatformContext _db = new CiPlatformContext();

        #region Mission List Init
        [CheckSession]
        public IActionResult MissionListing(int pg = 1)
        {
            MissionListingModel model = new MissionListingModel();

            #region Fill Country Drop-down
            List<SelectListItem> list = new List<SelectListItem>();
            var temp = _db.Countries.Where(x => x.DeletedAt == null).AsEnumerable().ToList();
            foreach (var item in temp)
            {
                list.Add(new SelectListItem() { Text = item.Name, Value = item.CountryId.ToString() });
            }
            model.countrys = list;
            #endregion Fill Country Drop-down

            #region Fill City Drop-down
            List<SelectListItem> list3 = new List<SelectListItem>();
            var temp3 = _db.Cities.Where(x => x.DeletedAt == null).AsEnumerable().ToList();
            foreach (var item in temp3)
            {
                list3.Add(new SelectListItem() { Text = item.Name, Value = item.CityId.ToString() });
            }
            model.citys = list3;
            #endregion Fill Country Drop-down

            #region Fill Theme Drop-down
            List<SelectListItem> list1 = new List<SelectListItem>();
            var temp1 = _db.Themes.Where(x => x.DeletedAt == null).AsEnumerable().ToList();
            foreach (var item in temp1)
            {
                list1.Add(new SelectListItem() { Text = item.Title, Value = item.ThemeId.ToString() });
            }
            model.themes = list1;
            #endregion Fill Theme Drop-down

            #region Fill Skill Drop-Down
            List<SelectListItem> list2 = new List<SelectListItem>();
            var temp2 = _db.Skills.Where(x => x.DeletedAt == null).AsEnumerable().ToList();
            foreach (var item in temp2)
            {
                list2.Add(new SelectListItem() { Text = item.SkillName, Value = item.SkillId.ToString() });
            }
            model.skills = list2;
            #endregion Fill Skill Drop-Down

            var cardData = new List<MissionCardModel>();

            var tempMission = _db.Missions.Where(x => x.DeletedAt == null && x.Status == 1).AsEnumerable().ToList();
            model.TotalMission = tempMission.Count();
            foreach (var item in tempMission)
            {
                cardData.Add(CreateCard(item));
            }
            model.missionsCard = cardData;

            const int pageSize = 9;
            int recsCount = tempMission.Count();
            var pager = new Pager(recsCount, pg, pageSize);
            int recSkip = (pg - 1) * pageSize;

            var data = cardData.Skip(recSkip).Take(pager.PageSize).ToList();
            model.missionsCard = data;
            this.ViewBag.Pager = pager;

            return View(model);
        }
        #endregion Mission List Init

        #region Mission Filter
        [HttpPost]
        public PartialViewResult Filter(List<int>? CountryId, List<int>? CityId, List<int>? ThemeId, List<int>? SkillId, string? searchText, int? sort, int pg = 1)
        {
            var cardData = new List<MissionCardModel>();
            var tempMission = new List<Mission>();

            #region Search

            if (searchText != null)
            {
                var missions = _db.Missions.Where(x => x.DeletedAt == null && x.Status == 1 && x.Title.Contains(searchText)).AsEnumerable().ToList();
                foreach (var m in missions)
                {
                    bool t = tempMission.Any(x => x.MissionId == m.MissionId);
                    if (t == false)
                    {
                        tempMission.Add(m);
                    }
                }
            }

            #endregion Search

            #region Filter Country
            if (CountryId.Count != 0)
            {
                foreach (var n in CountryId)
                {
                    var missions = _db.Missions.Where(x => x.DeletedAt == null && x.Status == 1 && x.CountryId == n).AsEnumerable().ToList();
                    foreach (var m in missions)
                    {
                        bool t = tempMission.Any(x => x.MissionId == m.MissionId);
                        if (t == false)
                        {
                            tempMission.Add(m);
                        }
                    }
                }
            }
            #endregion Filter Country

            #region Filter City
            if (CityId.Count != 0)
            {
                foreach (var n in CityId)
                {
                    var missions = _db.Missions.Where(x => x.DeletedAt == null && x.Status == 1 && x.CityId == n).AsEnumerable().ToList();
                    foreach (var m in missions)
                    {
                        bool t = tempMission.Any(x => x.MissionId == m.MissionId);
                        if (t == false)
                        {
                            tempMission.Add(m);
                        }
                    }
                }
            }
            #endregion Filter City

            #region FIlter Theme
            if (ThemeId.Count != 0)
            {
                foreach (var n in ThemeId)
                {
                    var missions = _db.Missions.Where(x => x.DeletedAt == null && x.Status == 1 && x.ThemeId == n).AsEnumerable().ToList();

                    foreach (var m in missions)
                    {
                        bool t = tempMission.Any(x => x.MissionId == m.MissionId);
                        if (t == false)
                        {
                            tempMission.Add(m);
                        }
                    }
                }
            }
            #endregion FIlter Theme

            #region Filter Skill
            if (SkillId.Count != 0)
            {
                foreach (var n in SkillId)
                {
                    var missions = new List<Mission>();
                    var missionList = _db.MissionSkills.Where(x => x.SkillId == n).Select(m => m.MissionId).AsEnumerable().ToList();
                    foreach (var mission in missionList)
                    {
                        missions.Add(_db.Missions.FirstOrDefault(x => x.MissionId == mission));
                    }
                    foreach (var m in missions)
                    {
                        bool t = tempMission.Any(x => x.MissionId == m.MissionId);
                        if (t == false)
                        {
                            tempMission.Add(m);
                        }
                    }
                }
            }
            #endregion Filter Skill

            #region Default Mission
            if (CountryId.Count == 0 && CityId.Count == 0 && ThemeId.Count == 0 && SkillId.Count == 0 && searchText == null)
            {
                tempMission = _db.Missions.Where(x => x.DeletedAt == null && x.Status == 1).AsEnumerable().ToList();
            }
            #endregion Default Mission

            #region Create Card
            foreach (var item in tempMission)
            {
                cardData.Add(CreateCard(item));
            }
            #endregion Create Card

            #region Sort Data
            if (sort != null)
            {
                switch (sort)
                {
                    case 1:
                        cardData = cardData.OrderByDescending(x => x.mission.CreatedAt).ToList();
                        break;
                    case 2:
                        cardData = cardData.OrderBy(x => x.mission.CreatedAt).ToList();
                        break;
                    case 3:
                        cardData = cardData.OrderBy(x => x.seatsLeft).ToList();
                        break;
                    case 4:
                        cardData = cardData.OrderByDescending(x => x.seatsLeft).ToList();
                        break;
                    case 5:
                        cardData = cardData.OrderByDescending(x => x.favMission).ToList();
                        break;
                    case 6:
                        cardData = cardData.OrderByDescending(x => x.mission.Deadline).ToList();
                        break;
                }
            }
            #endregion Sort Data

            const int pageSize = 9;
            int recsCount = tempMission.Count();
            var pager = new Pager(recsCount, pg, pageSize);
            int recSkip = (pg - 1) * pageSize;

            var data = cardData.Skip(recSkip).Take(pager.PageSize).ToList();
            cardData = data;
            this.ViewBag.Pager = pager;

            return PartialView("_MissionGridPartial", cardData);
        }
        #endregion Mission Filter

        #region Fav Mission
        [HttpPost]
        public JsonResult FavMission(int id, int fav)
        {
            if (fav == 1)
            {
                var favMission = new FavouriteMission();
                favMission.MissionId = id;
                favMission.UserId = long.Parse(HttpContext.Session.GetString("UserId"));
                _db.FavouriteMissions.Add(favMission);
                _db.SaveChanges();
            }
            else
            {
                var favMission = _db.FavouriteMissions.FirstOrDefault(x => x.MissionId == id && x.UserId == int.Parse(HttpContext.Session.GetString("UserId")) && x.DeletedAt == null);
                favMission.DeletedAt = DateTime.Now;
                _db.FavouriteMissions.Update(favMission);
                _db.SaveChanges();
            }

            return Json("True");
        }
        #endregion Fav Mission

Backend/CIPlatform/Views/Mission/MissionListing.cshtml
@using CIPlatform.Models
@model MissionListingModel

@{
    Pager pager = new Pager();

    int pageNo = 0;
    if (ViewBag.Pager != null)
    {
        pager = ViewBag.Pager;
        pageNo = pager.CurrentPage;
    }
}

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script data-main="dist/js/" src="js/require.min.js"></script>
<script src="~/js/vertuleSelect.js"></script>
@*<script src="https://cdn.jsdelivr.net/npm/virtual-select-plugin@1.0.33/dist/virtual-select.min.js"></script>*@
<script>

    setTimeout(alertFunc, 1000);
    function alertFunc(){
        VirtualSelect.init({
            ele: '#ddlCountry',
            dropboxWidth: '170px'
        });
        VirtualSelect.init({
            ele: '#ddlCity',
            dropboxWidth: '170px'
        });
        VirtualSelect.init({
            ele: '#ddlTheme',
            dropboxWidth: '170px'
        });
        VirtualSelect.init({
            ele: '#ddlSkill',
            dropboxWidth: '170px'
        });
    }

    $(document).ready(function () {

        $("#countryDiv").change(function() {
            FilterTag("#ddlCountry");
            Filter();
        });
        $("#cityDiv").change(function () {
            FilterTag("#ddlCity");
            Filter();
        });
        $("#themeDiv").change(function () {
            FilterTag("#ddlTheme");
            Filter();
        });
        $("#skillDiv").change(function () {
            FilterTag("#ddlSkill");
            Filter();
        });
        $("#ddlShort").change(function (){
            Filter();
        });
    });

     function Search(){
            Filter();
     }

     function favMission(Missionid,Missionfav){
         $.ajax({
            url: '/Mission/FavMission',
            type:'POST',
            dataType:'json',
            data:{id:Missionid,fav:Missionfav},
            success:function(d){
                Filter();
            },
            error:function(){
                alert('Error');
            }
         });
     }

     function ApplyMission(MissionId){
         $.ajax({
            url: '/Mission/ApplyMission',
            type:'POST',
            dataType:'json',
            data:{id:MissionId},
            success:function(d){
                Filter();
                alert(d);
            },
            error:function(){
                alert('Error');
            }
         });
     }

     function FilterTag(str){
         var a = document.querySelector(str).getSelectedOptions();
         $(str + "Div").empty();
         $.each(a,function(i,text){
            $(str + "Div").append('<button type="button" class="btn btn-sm btn-outline-dark rounded-pill mt-1 me-2"><span class="text-wrap">'+ text.label +'</span><i class="bi bi-x"></i></button>') ;
         });
     }

    function Filter(){
        let searchParams = new URLSearchParams(window.location.search)
        let param = searchParams.get('pg');
        var country = $("#ddlCountry").val();
        var city = $("#ddlCity").val();
        var theme = $("#ddlTheme").val();
        var skill = $("#ddlSkill").val();
        var search = $("#box").val();
        var Sort = $("#ddlShort").val();
         $.ajax({
            url: '/Mission/Filter',
            type:'POST',
            dataType:'html',
            data:{CountryId: country,CityId:city,ThemeId:theme,SkillId:skill,searchText:search,sort:Sort,pg:param},
            success:function(d){
                $("#missionGrid").empty();
                $("#missionGrid").html(d);
            },
            error:function(){
                alert('Error');
            }
         });
    }

</script>



<div class="container-lg">
    <nav class="navbar navbar-expand-lg py-0">
        <div class="container-fluid">
            <div class="collapse navbar-collapse" id="navbarScroll">
                <form class="form-horizontal me-auto mb-2 mb-lg-0 d-none d-lg-block ">
                    <input type="search" id="box" onkeyup="Search()" class="form-control customshadow"
                           style="width: 40vw; border: 0px; font-family:Arial, FontAwesome;"
                           placeholder=" &#xF002; Search Mission..." aria-label="Search" />
                </form>
                <ul class="navbar-nav ms-auto my-2 my-lg-0 navInline">
                    <li class="nav-item dropdown border-lg-left border-sm-left-0 p-2">
                        <div id="countryDiv">
                            <select id="ddlCountry" class="border-0" multiple asp-items="Model.countrys"
                                    placeholder="Country"
                                    data-search="true">
                            </select>
                        </div>
                    </li>
                    <li class="nav-item dropdown border-sm-left-0 border-lg-left p-2">

                        <div id="cityDiv">
                            <select id="ddlCity" class="border-0" multiple asp-items="Model.citys"
                                    placeholder="City"
                                    data-search="true" data-silent-initial-value-set="true">
                            </select>
                        </div>

                        @*  <select class="form-select border-0" id="ddlCity" asp-items="@Model.citys" aria-label="Default select example">
                            <option selected>City</option>
                            </select>*@

                    </li>
                    <li class="nav-item dropdown border-lg-left border-sm-left-0 p-2">

                        <div id="themeDiv">
                            <select id="ddlTheme" class="border-0" multiple asp-items="Model.themes"
                                    placeholder="Theme"
                                    data-search="true" data-silent-initial-value-set="true">
                            </select>
                        </div>

                        @*     <select class="form-select border-0" id="ddlTheme" asp-items="@Model.themes" aria-label="Default select example">
                            <option selected>Theme</option>
                            </select>*@
                    </li>
                    <li class="nav-item dropdown border-lg-left border-lg-right border-sm-left-0 border-sm-right-0 p-2">

                        <div id="skillDiv">
                            <select id="ddlSkill" class="border-0" multiple asp-items="Model.skills"
                                    placeholder="Skills"
                                    data-search="true" data-silent-initial-value-set="true">
                            </select>
                        </div>

                        @*<select class="form-select border-0" id="ddlSkill" asp-items="@Model.skills" style="width:100px" aria-label="Default select example">
                            <option selected>Skill</option>
                            </select>*@
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</div>
<hr class="d-none d-lg-block" style="margin: 0px;">




<div class="container-lg">

    <div class="mt-md-3 mb-md-3">

        <span id="ddlCountryDiv"></span>
        <span id="ddlCityDiv"></span>
        <span id="ddlThemeDiv"></span>
        <span id="ddlSkillDiv"></span>

        <a class="ms-2" style="text-decoration: none; color:black;" href="MissionListing">
            Clear all
        </a>
    </div>

    <nav class="navbar navbar-expand-lg">
        <div class="container-fluid">
            <label class="fs-4">Explore <span class="fw-semibold">@Model.TotalMission missions</span></label>
            <ul class="navbar-nav ms-auto my-2 my-lg-0 navbar-nav-scroll">

                <li class="nav-item me-md-4 d-none d-lg-block">
                    <span id="SortDiv">
                        <select id="ddlShort" placeholder="Sort By">
                            <option selected>Sort By</option>
                            <option value="1">Newest</option>
                            <option value="2">Oldest</option>
                            <option value="3">Lowest available seats</option>
                            <option value="4">Highest available seats</option>
                            <option value="5">Sort by my favourite</option>
                            <option value="6">Sort by deadline</option>
                        </select>
                    </span>

                </li>

                <li class="nav-item ms-2 d-none d-lg-block">
                    <button class="rounded-circle btn btn-light"><i class="bi bi-grid"></i></button>
                </li>
                <li class="nav-item ms-1 d-none d-lg-block">
                    <button class="rounded-circle btn btn-light"><i class="bi bi-list"></i></button>
                </li>
            </ul>
        </div>
    </nav>


    <div id="missionGrid">
        @{
            Html.RenderPartial("_MissionGridPartial", Model.missionsCard);
        }
    </div>


    <nav aria-label="Page navigation example mt-5 mb-5">

        @if (pager.TotalPages > 0)
        {
            <ul class="pagination justify-content-center">

                @if (pager.CurrentPage > 1)
                {
                    <li class="page-item">
                        <a class="page-link" asp-controller="Mission" asp-action="MissionListing" asp-route-pg="1">First</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" asp-controller="Mission" asp-action="MissionListing" asp-route-pg="@(pager.CurrentPage - 1)">Previous</a>
                    </li>
                }

                @for (var pge = pager.StartPage; pge <= pager.EndPage; pge++)
                {
                    <li class="page-item @(pge == pager.CurrentPage ? "active" : "")">
                        <a class="page-link" asp-controller="Mission" asp-action="MissionListing" asp-route-pg="@pge">@pge</a>
                    </li>
                }

                @if (pager.CurrentPage < pager.TotalPages)
                {
                    <li class="page-item">
                        <a class="page-link" asp-controller="Mission" asp-action="MissionListing" asp-route-pg="@(pager.CurrentPage + 1)">Next</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" asp-controller="Mission" asp-action="MissionListing" asp-route-pg="@(pager.TotalPages)">Last</a>
                    </li>
                }
            </ul>
        }
    </nav>
</div>

Backend/CIPlatform/Views/Mission/_CoWorkerPartial.cshtml
@using CIPlatform.DataModels
@model Mission

<div class="modal fade" id="SuggestWorker">
    <div class="modal-dialog">
        <div class="modal-content">
            <form id="modalForm" method="post" action="SuggestCoWorker">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Suggest Co-Worker</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal"
                            aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <input asp-for="MissionId" hidden />
                        <div class="col-12 mt-3">
                            <label>Email</label>
                            <input type="text" class="form-control" name="WorkerEmail" required="" placeholder="Enter Email" id="" />
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-secondary rounded-pill"
                            data-bs-dismiss="modal">
                        Cancel
                    </button>
                    <button type="submit" class="btn btn-outline-warning rounded-pill">Send</button>
                </div>
            </form>
        </div>
    </div>
</div>

Backend/CIPlatform/Views/Mission/_MissionGridPartial.cshtml
@using CIPlatform.DataModels;
@model List<MissionCardModel>

<script>
        $(function () {

        var PlaceHolderElement = $('#PlaceHolderHere');
        $('button[data-toggle="ajax-modal"]').click(function (event) {

            var url = $(this).data('url');
            var decodeUrl = decodeURIComponent(url);
            console.log(url);
            $.get(decodeUrl).done(function (data) {
                PlaceHolderElement.html(data);
                PlaceHolderElement.find('.modal').modal('show');
            })
        })

        PlaceHolderElement.on('click', '[data-bs-save="modal"]', function (event) {

            var formData = new FormData($('#modalForm').get(0));
            var form = $(this).parents('.modal').find('form');
            var actionUrl = form.attr('action');
            $.ajax({
                url: "/Mission/" + actionUrl,
                type: "POST",
                data: formData,
                processData: false,
                contentType: false,
                dataType: "json",
                success: function (data) {
                    PlaceHolderElement.find('.modal').modal('hide');
                }

            })
            PlaceHolderElement.find('.modal').modal('hide');
        })

    })
</script>
<div class="row mb-5">

    @foreach (var item in Model)
    {
        <div class="col-sm-12 col-md-6 col-lg-4 mb-4">

            <div class="card cardWidth shadow h-100">
                <img src="@Url.Content(@item.CardImg)" class="home-card-img" alt="...">
                <div class="card-body">
                    <div class="cardTitleAction">
                        <span class="text-wrap btn btn-sm rounded-pill cardTitleSubAction"
                          style="background-color: white; color: #757575; ">
                            @item.theme

                        </span>
                    </div>
                    <button type="button" style="color: white; background-color: black; "
                        class="btn btn-sm btn-outline-dark float-end rounded-pill cardLocation">
                        <i class="bi bi-geo-alt"></i>
                        <span class="text-wrap">
                            @item.country
                        </span>
                    </button>
                    @if (item.favMission == 0)
                    {
                        <button type="button" onclick="favMission(@item.mission.MissionId,1)" style="color: white; background-color: black; "
                        class="btn btn-sm btn-outline-dark float-end rounded-pill cardLike">
                            <i class="bi bi-suit-heart"></i>
                        </button>
                    }
                    else
                    {
                        <button type="button" onclick="favMission(@item.mission.MissionId,0)" style="color: white; background-color: black; "
                        class="btn btn-sm btn-outline-dark float-end rounded-pill cardLike">
                            <i class="bi bi-heart-fill text-danger"></i>
                        </button>
                    }



                    <button type="button" data-toggle="ajax-modal" data-target="#SuggestWorker" style="color: white; background-color: black;"
                        class="btn btn-sm btn-outline-dark float-end rounded-pill cardAddPeople" data-url="@Url.Action("SuggestCoWorker", "Mission" , new{id = @item.mission.MissionId})">
                        <i class="bi bi-person-plus"></i>
                    </button>
                    <div id="PlaceHolderHere"></div>

                    <h5 class="card-title cardTitle">@item.mission.Title</h5>
                    <p class="card-text cardText">@item.mission.ShortDescription</p>
                    <div class="mt-1 mb-4">
                        <span class="float-start">@item.mission.OrganizationName</span>
                        <span class="float-end">
                            <div class="Stars" style="--rating: @item.avgRateing;" aria-label="Rating of this product is @item.avgRateing out of 5."></div>
                        </span>
                    </div>
                    <br>
                    <div>
                        <div class="cardAction">
                            <span class="text-wrap btn btn-sm btn-outline-dark rounded-pill subAction"
                              style="background-color: white; color: #757575; ">
                                @if (@item.mission.StartDate != null)
                                {
                                    <span> From @Convert.ToDateTime(item.mission.StartDate).ToString("dd/MM/yyyy") until @Convert.ToDateTime(item.mission.EndDate).ToString("dd/MM/yyyy")</span>
                                }
                                else
                                {
                                    <span>Ongoing Opportunity</span>
                                }
                            </span>
                        </div>
                        <hr style=" z-index: -12; margin-left: -4.3%; margin-right: -4.3%;">
                    </div>

                    <div class="row mt-4">
                        <div class="col-6 text-wrap">
                            <span class="cardDedlineSeats"><i class="bi bi-person-check me-2 ms-3"></i>@item.seatsLeft</span>
                            <br style="margin: 0px;">
                            <span class="cardSmallText ms-4">Seats left</span>
                        </div>
                        @if (item.mission.Deadline != null)
                        {
                            <div class="col-6 text-wrap">
                                <span class="cardDedlineSeats"><i class="bi bi-clock me-2 ms-3"></i>@Convert.ToDateTime(item.mission.Deadline).ToString("dd/MM/yyyy")</span>
                                <br style="padding: 0px;">
                                <span class="cardSmallText ms-5">Deadline</span>
                            </div>
                        }
                        else
                        {
                            <div class="col-1"><i class="bi bi-vinyl"></i></div>
                            <div class="col-5 text-wrap d-inline">
                                <span class="progress" style="height: 10px; margin-top: 8px; width: 100%;">
                                    <span class="progress-bar bg-warning" role="progressbar" aria-label="Basic example"
                                  style="width: @item.progressBar%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="75">
                                    </span>
                                </span>
                                <span class="cardSmallText ms-5">
                                        @((@item.progressBar * @item.goalMission.GoalValue)/100)
                                     Achieved</span>
                            </div>
                        }
                    </div>
                    <hr style=" margin-left: -4.3%; margin-right: -4.3%;">

                    <div class="cardAction mb-1">
                        @if (item.mission.Deadline > DateTime.Now && item.seatsLeft > 0)
                        {
                            <button type="button" onclick="ApplyMission(@item.mission.MissionId)" class="btn btn-outline-warning rounded-pill" style="margin-left: auto; margin-right: auto;">
                                <span class="text-wrap">Apply</span>
                                <i class="bi bi-arrow-right ms-2"></i>
                            </button>
                        }
                        else if(item.mission.MissionType == 2 && item.seatsLeft > 0 && item.progressBar < 100)
                        {
                            <button type="button" onclick="ApplyMission(@item.mission.MissionId)" class="btn btn-outline-warning rounded-pill" style="margin-left: auto; margin-right: auto;">
                                <span class="text-wrap">Apply</span>
                                <i class="bi bi-arrow-right ms-2"></i>
                            </button>
                        }

                        <button type="button" onclick="return location.href=' @Url.Action("MisionDetail","Mission",new {id=@item.mission.MissionId}) '" class="btn btn-outline-warning rounded-pill" style="margin-left: auto; margin-right: auto;">
                            <span class="text-wrap">Detail</span>
                        </button>
                    </div>
                </div>
            </div>


        </div>
    }

</div>